const games = [
    {title: 'Gamedle',  url: 'https://www.gamedle.wtf/', description: 'Guess the videogame by its cover, every day a new game.', image: 'images/gamedle.jpg', country: '', tags: ['game', 'word'], stars:'',},
    {title: 'Termo',  url: 'https://term.ooo', description: 'Brazilian Wordly with a extra features and lots of users stats', image: 'images/termooo.png', country: 'br', tags: ['word'], stars:'',},
    {title: 'Dungleon', url: 'https://www.dungleon.com/', description: "Guess the dungeon's composition in 6 guesses.", image: 'images/dungeon.png', country: '', tags: ['video game', 'dungeon'], stars:'', },
    {title: 'Deccodr', url: 'https://decoddr.cc/', description: 'Every day a single code to be break. Pay attention to the hint and good lucky!!!', image: 'images/decoddr.jpeg', country: 'br', tags: ['code', 'math'], stars:'', },
    {title: 'Conexo.ws', url: 'https://conexo.ws/', description: 'Form 4 groups of 4 words that have something in common.', image: 'images/conexo-ws.jpg', country: '', tags: ['connect', 'words'], stars:'', },
    {title: 'Framed.wtf', url: 'https://framed.wtf/', description: 'Film frames shown daily. Try to figure out which movie.', image: 'images/framed.jpg', country: '', tags: ['frame', 'movie'], stars:'', },
    {title: 'Estadi.ooo',  url: 'https://estadi.ooo/', description: 'Brazilian and Portuguese game to find out stadiums', image: 'images/estadiooo.jpg', country: 'br', tags: ['stadium', 'sport', 'football'], stars:'',},
    {title: 'Cerebrle Sequence', url: 'https://cerebrle.io/sequence', description: 'Find out the sequence of the day, with many levels difficulty.', image: 'images/cerebrle-sequence.jpg', country: '', tags: ['sequence'], stars:'', },
    {title: 'Episode.wtf', url: 'https://episode.wtf/', description: 'The image provided to guess the name of the TV show.', image: 'images/episode-wtf.png', country: '', tags: ['episode', 'tv', 'show'], stars:'', },
    {title: 'Novel', url: 'https://novel-app-web.vercel.app/', description: 'You like Soap Opera? Five shoots to find out a soap opera of the day.', image: 'images/novel.jpeg', country: 'br', tags: ['soap opera', 'word'], stars:'', },
    {title: 'Moviedle', url: 'https://likewisetv.com/arcade/moviedle', description: 'The Daily Guess That Movie game! ', image: 'images/moviedle.jpg', country: '', tags: ['movie', 'word'], stars:'', },
    {title: 'Name That Ride', url: 'https://www.namethatride.com/', description: '20 seconds to find out the car that will slowly reveal itself on the screen.', image: 'images/ride.jpg', country: '', tags: ['car', 'ride', 'word'], stars:'', },
    {title: 'Footbl 5', url: 'https://playfootball.games/footbl/5', description: 'Same as Wordle but with soccer players from Europe League', image: 'images/footbl.jpg', country: '', tags: ['music'], stars:'', },
    {title: 'Nerdle', url: 'https://nerdlegame.com/', description: 'Find out what the mathematical operation', image: 'images/game-nerdle.jpg', country: '', tags: ['nerd', 'operation', 'math'], stars:'', },
    {title: 'Plotwords', url: 'https://plotwords.com/', description: 'Guess the name of the movie using as few plot keywords as possible!', image: 'images/plotwords.png', country: '', tags: ['movies', 'word'], stars:'', },
    {title: 'Musicle', url: 'https://musicle.app/', description: 'This is Musicle, the music-guessing game. It comes in several flavors!', image: 'images/musicle.jpg', country: '', tags: ['music'], stars:'', },
    {title: 'Actorle', url: 'https://actorle.com/', description: 'Guess the actor of the day based on their movies.', image: 'images/actorle.jpg', country: '', tags: ['actor', 'movie'], stars:'', },
    {title: 'Cerebrle Number', url: 'https://cerebrle.io/number', description: 'Game of number memory game with tips and tricks to improve your skill', image: 'images/cerberle-number.jpg', country: '', tags: ['number', 'memory'], stars:'', },
    {title: 'Wordle', url: 'https://www.nytimes.com/games/wordle/index.html', description: 'Simple word daily guessing game', image: 'images/wordle.jpg', country: '', tags: ['words'], stars:'', },
    {title: 'Contexto', url: 'https://contexto.me/', description: 'Guess what word of the day with a context', image: 'images/contexto.jpg', country: 'br', tags: ['word', 'context'], stars:'', },
    {title: 'Flagle', url: 'https://www.flagle.io/', description: 'You know all flags of all countries, so this is a perfect daily game for you', image: 'images/flagle.jpg', country: '', tags: ['flag', 'world','word'], stars:'', },
    {title: 'Angle', url: 'https://angle.wtf/', description: 'Can you discover what angle is showing on screen?', image: 'images/cerberle-angle.jpg', country: '', tags: ['angle', 'math'], stars:'', },
    {title: 'Cerebrle Word', url: 'https://cerebrle.io/word', description: 'Game of words memory game', image: 'images/cerberle-word.jpg', country: '', tags: ['word', 'memory'], stars:'', },
    {title: 'Letreco', url: 'https://www.gabtoschi.com/letreco/', description: 'In this brazilian game you have to find out word daily', image: 'images/letreco.jpg', country: 'br', tags: ['word', 'sequence', 'memory'], stars:'', },
    {title: 'Posterdle', url: 'https://posterdle.io/', description: 'A daily puzzle game base on movie posters.', image: 'images/posterdle.jpg', country: 'br', tags: ['poster', 'movie', 'word'], stars:'', },
    {title: 'Globle Game', url: 'https://globle-game.com/game', description: 'Enter the name of any country to make your first guess.', image: 'images/globle.jpg', country: '', tags: ['globle', 'world'], stars:'', },
    {title: 'Numble.wtf', url: 'https://numble.wtf/', description: 'Try and get to the target using only the numbers provided.', image: 'images/numble-wtf.png', country: '', tags: ['number'], stars:'', },
];

export default games;