const games = [
    {title: 'Gamedle',  url: 'https://www.gamedle.wtf/', description: 'Guess the videogame by its cover, every day a new game.', image: '', country: '', tags: ['game', 'word'], stars: 5,},
    {title: 'Termo',  url: 'https://term.ooo', description: 'Brazilian Wordly with a extra features and lots of users stats', image: '', country: 'br', tags: ['word'], stars: 5,},
    {title: 'Dungleon', url: 'https://www.dungleon.com/', description: "Guess the dungeon's composition in 6 guesses.", image: '', country: '', tags: ['video game', 'dungeon'], stars: 4, },
    {title: 'Deccodr', url: 'https://decoddr.cc/', description: 'Every day a single code to be break. Pay attention to the hint and good lucky!!!', image: '', country: 'br', tags: ['code', 'math'], stars: 4, },
    {title: 'Conexo.ws', url: 'https://conexo.ws/', description: 'Form 4 groups of 4 words that have something in common.', image: '', country: '', tags: ['connect', 'words'], stars: 4, },
    {title: 'Novel', url: 'https://novel-app-web.vercel.app/', description: 'You like Soap Opera? Five shoots to find out a soap opera of the day.', image: '', country: 'br', tags: ['soap opera', 'word'], stars: 4, },
    {title: 'Framed.wtf', url: 'https://framed.wtf/', description: 'Film frames shown daily. Try to figure out which movie.', image: '', country: '', tags: ['frame', 'movie'], stars: 5, },
    {title: 'Estadi.ooo',  url: 'https://estadi.ooo/', description: 'Brazilian and Portuguese game to find out stadiums', image: '', country: 'br', tags: ['stadium', 'sport', 'football'], stars: 4,},
    {title: 'Cerebrle Sequence', url: 'https://cerebrle.io/sequence', description: 'Find out the sequence of the day, with many levels difficulty.', image: '', country: '', tags: ['sequence'], stars: 4, },
    {title: 'Episode.wtf', url: 'https://episode.wtf/', description: 'The image provided to guess the name of the TV show.', image: '', country: '', tags: ['episode', 'tv', 'show'], stars: 4, },
    {title: 'Moviedle', url: 'https://likewisetv.com/arcade/moviedle', description: 'The Daily Guess That Movie game! ', image: '', country: '', tags: ['movie', 'word'], stars: 3, },
    {title: 'Name That Ride', url: 'https://www.namethatride.com/', description: '20 seconds to find out the car that will slowly reveal itself on the screen.', image: '', country: '', tags: ['car', 'ride', 'word'], stars: 3, },
    {title: 'Footbl 5', url: 'https://playfootball.games/footbl/5', description: 'Same as Wordle but with soccer players from Europe League', image: '', country: '', tags: ['music'], stars: 4, },
    {title: 'Nerdle', url: 'https://nerdlegame.com/', description: 'Find out what the mathematical operation', image: '', country: '', tags: ['nerd', 'operation', 'math'], stars: 4, },
    {title: 'Plotwords', url: 'https://plotwords.com/', description: 'Guess the name of the movie using as few plot keywords as possible!', image: '', country: '', tags: ['movies', 'word'], stars: 4, },
    {title: 'Musicle', url: 'https://musicle.app/', description: 'This is Musicle, the music-guessing game. It comes in several flavors!', image: '', country: '', tags: ['music'], stars: 5, },
    {title: 'Actorle', url: 'https://actorle.com/', description: 'Guess the actor of the day based on their movies.', image: '', country: '', tags: ['actor', 'movie'], stars: 4, },
    {title: 'Cerebrle Number', url: 'https://cerebrle.io/number', description: 'Game of number memory game with tips and tricks to improve your skill', image: '', country: '', tags: ['number', 'memory'], stars: 3, },
    {title: 'Wordle', url: 'https://www.nytimes.com/games/wordle/index.html', description: 'Simple word daily guessing game', image: '', country: '', tags: ['words'], stars: 5, },
    {title: 'Contexto', url: 'https://contexto.me/', description: 'Guess what word of the day with a context', image: '', country: 'br', tags: ['word', 'context'], stars: 5, },
    {title: 'Flagle', url: 'https://www.flagle.io/', description: 'You know all flags of all countries, so this is a perfect daily game for you', image: '', country: '', tags: ['flag', 'world','word'], stars: 5, },
    {title: 'Angle', url: 'https://angle.wtf/', description: 'Can you discover what angle is showing on screen?', image: '', country: '', tags: ['angle', 'math'], stars: 3, },
    {title: 'Cerebrle Word', url: 'https://cerebrle.io/word', description: 'Game of words memory game', image: '', country: '', tags: ['word', 'memory'], stars: 3, },
    {title: 'Letreco', url: 'https://www.gabtoschi.com/letreco/', description: 'In this brazilian game you have to find out word daily', image: '', country: 'br', tags: ['word', 'sequence', 'memory'], stars: 4, },
    {title: 'Posterdle', url: 'https://posterdle.io/', description: 'A daily puzzle game base on movie posters.', image: '', country: 'br', tags: ['poster', 'movie', 'word'], stars: 3, },
    {title: 'Globle Game', url: 'https://globle-game.com/game', description: 'Enter the name of any country to make your first guess.', image: '', country: '', tags: ['globle', 'world'], stars: 4, },
    {title: 'Numble.wtf', url: 'https://numble.wtf/', description: 'Try and get to the target using only the numbers provided.', image: '', country: '', tags: ['number'], stars: 4, },
];

export default games;